### ISSUE TITLE
目前的版本引入有问题

### ISSUE THREAD

**Issue by lhh-sofy** [canyara/react-native-bugly#1]
目前版本是0.0.1？,yarn add时候，文件不全

**Comment by canyara** [comment]
没有上npm
这样使用
`yarn add git+https://github.com/canyara/react-native-bugly.git`

目前不支持android

**Comment by lhh-sofy** [comment]
这样使用啊，好的 ，多谢。。那什么时候可以使用安卓呢。还有就是我怎么配置info.plist，有实例么？

**Comment by canyara** [comment]
> 这样使用啊，好的 ，多谢。。那什么时候可以使用安卓呢。还有就是我怎么配置info.plist，有实例么？

配置参照官方Info.plist就好了
安卓版本等我用了会更新的
