### ISSUE TITLE
能增加set 渠道标识 的方法吗

### ISSUE THREAD

**Issue by orzhtml** [canyara/react-native-bugly#5]
能增加set 渠道标识 的方法吗

**Comment by canyara** [comment]
> 能增加set 渠道标识 的方法吗

可以按照bugly的使用方法增加渠道

**Comment by orzhtml** [comment]
> > 能增加set 渠道标识 的方法吗
> 
> 可以按照bugly的使用方法增加渠道

我需要用rn

**Comment by canyara** [comment]
> > > 能增加set 渠道标识 的方法吗
> > 
> > 
> > 可以按照bugly的使用方法增加渠道
> 
> 我需要用rn

欢迎提交pr
