### ISSUE TITLE
经测试0.57.5无效

### ISSUE THREAD

**Issue by hanwenbo** [canyara/react-native-bugly#7]
link了
1.#import "RNBugly.h" 找不到库
2.手动加上

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNBugly", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

安卓就没测了

**Comment by canyara** [comment]
0.57.5可以运行
如果会报错可以在项目根目录执行:
`node node_modules/react-native-bugly/scripts/postlink`

**Comment by hanwenbo** [comment]
@canyara 嗯嗯 今天很神奇 执行您的方法可以了 那天我也执行了 不可以


请问，plist已经设置了  为什么还要重新设置呢？意思是可以重新定义吗？
```jsx
import RNBugly from "react-native-bugly";

RNBugly.updateAppVersion(version);
RNBugly.setUserIdentifier(userId);
```

**Comment by hanwenbo** [comment]
这些是安卓的配置  您补到文档上吧
```jsx
<application
    <!-- 配置APP ID -->
    <meta-data
            android:name="BUGLY_APPID"
            android:value="<APP_ID>" />
    <!-- 配置APP版本号 -->
    <meta-data
            android:name="BUGLY_APP_VERSION"
            android:value="<APP_Version>" />
    <!-- 配置APP渠道号 -->
    <meta-data
            android:name="BUGLY_APP_CHANNEL"
            android:value="<APP_Channel>" />
    <!-- 配置Bugly调试模式（true或者false）-->
    <meta-data
            android:name="BUGLY_ENABLE_DEBUG"
            android:value="<isDebug>" />
</application>
```

**Comment by hanwenbo** [comment]
跑着跑着 又报错 了

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNBugly", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

找不到规律

**Comment by hanwenbo** [comment]
安装卸载、重启电脑 等等 ios 都不可以哈，安卓完美运行

**Comment by zhuhengtan** [comment]
我RN0.59.5里面iOS没有问题，安卓有问题，0.55.4iOS和安卓都没问题

**Comment by zhuhengtan** [comment]
sorry我0.55.4是直接原生集成的SDK😅

**Comment by hanwenbo** [comment]
嗯呢 没见过这错误

**Comment by canyara** [comment]
> 嗯呢 没见过这错误

具体什么报错？其实插件就是很简单的wrap了一下bugly 
link的js脚本就是自动做了关联framework等接入 步骤 如果iOS脚本配置失败可以参考bugly文档手动设置一下

**Comment by canyara** [comment]
> 嗯呢 没见过这错误

iOS手动设置：
1. 项目Framework Search Paths中加入
`$(SRCROOT)/../node_modules/react-native-bugly/ios/RNBugly`
2. 将
`$(SRCROOT)/../node_modules/react-native-bugly/ios/RNBugly/Bugly.framework`
放入Link Binary With Libraries

**Comment by zhuhengtan** [comment]
其实不用这个插件，直接用cocoapods很方便哇

**Comment by canyara** [comment]
> 其实不用这个插件，直接用cocoapods很方便哇

那就要自己wrap啦 
module可以做成支持cocoapods + rn 集成的

**Comment by hanwenbo** [comment]
@canyara 我按你上面方法去测试下哈  后续给您回复 谢谢啊
